const { access } = require("fs")

const status_codes = {
    OK: 201,
    CREATE: 200,
    NOT_FOUND: 404,
    BAD_REQUEST: 400,
    INTERNAL_SERVER_ERROR: 500,
    UNAUTHORIZED: 401
}
const status_message = {
    OK: "Create",
    NOT_FOUND: "Not found",
    BAD_REQUEST: "Invalid request. Please check your input data.",
    INTERNAL_SERVER_ERROR: "Internal server error.",
    PHONE_NOT_FOUND: "Phone number not found.Please provide mail thru sendmail.",
    INVALID_OTP: "Invalid otp.",
    OTP_EXPIRE: "Otp exipre.",
    OTP_VERIFY: "Otp verify sucessfully.",
    SEND_OTP: "Otp send sucessfully.",
    OTP_REQUIRED: "Otp required.",
    EMAIL_REQUIRED: "Email is required.",
    EMAIL_NOT_FOUND: "Email not found.please send mail thru sendmail.",
    USER_NOT_FOUND: 'User not found',
    USER_LOGIN_SUCCESS: "User login suceessfully",
    EMAIL_ALREADY_EXICST: "Email alredy exicst.",
    NAME_REQUIRED: "Name is required.",
    USER_ALREADY_RAGISTER: "User already ragister",
    PHONE_REQUIRED: "Phone is required.",
    AGE_REQUIRED: "Age is required.",
    GENDER_REQUIRED: "Gender is required.",
    USERIMAGE_REQUIRED: "User image is required.",
    PASSWORD_REQUIRED: "Password is required.",
    INVALID_PASSWORD: "Invalid password",
    NOT_SAME__PASSWORD: "Password and Confirmpass are not same.",
    CONFIRM_PASSWORD: "Confirm password is required.",
    USER_CREATE_SUCCESS: "User create successfully.",
    PRODUCT_NAME_REQUIRE: "Product name is require.",
    PRODUCT_PRICE_REQUIRE: "Product price is require.",
    DESCRIPTION_REQUIRE: "Description is require.",
    CATEGORY_REQUIRE: "Category is require.",
    SUBCATEGORY_REQUIRE:"Subcategory is require",
    CATEGORY_ID_REQUIRE:"Category id is require",
    PRODUCT_NOT_CREATE: "Product not create.",
    PRODUCT_CREATE_SUCCESS: "Product create sucessfully.",
    PRODUCT_ALREDY_EXISCT: "Product alredy exisct.",
    PRODUCT_NOT_DELETE: "Product not delete.",
    PRODUCT_DELETE_SUCCESS: "Product delete successfully.",
    MISSING_TOKEN: "Token is missing, token is required",
    INVALID_TOKEN: "Invalid token",
    MAXIMUM_OTP_ATTEMPTS: "You’ve reached the maximum number of attempts. Please try again after 12 hours.",
    OTP_VALIDATION: "Please try again after 12 hours.",
    CATEGORY_ALREADY_EXISCT: "Category already exisct.",
    CATEGORY_CREATE_SUCCESS: "Category create sucessfully.",
    SUBCATEGORY_CREATE_SUCCESS: "Subcategory create sucessfully.",
    CATEGORY_NOT_SAVE: "Category not save.",
    SUBCATEGORY_NOT_SAVE: "Subcategory not save.",
    CATEGORY_NAME_REQUIRE: "Category name is require.",
    CATEGORY_NOT_UPDATE: "Category not update.",
    CATEGORY_GET_SUCCESS:"Categorydata get sucessfully",
    SUBCATEGORY_GET_SUCCESS:"Subcategorydata get sucessfully",
    CATEGORY_UPDATE_SUCESSFULLY: "Category update sucessfully.",
    CATEGORY_STATUS_UPDATE: "Category data update sucessfully.",
    CATEGORY_DELETE_SUCCESS:"Category dalete sucessfully.",
    SUBCATEGORY_NAME_REQUIRE:"Subcategory name is require.",
    SUBCATEGORY_ALREADY_EXISCT:"Subcategory already exisct.",
    SUBCATEGORY_NOT_FOUND:"Subcategory data not found.",
    SUBCATEGORY_NOT_DELETE:"Subcategory not delete.",
    SUBCATEGORY_DELETE_SUCCESS:"Subcategory data delete.",
    SUBCATEGORY_NOT_UPDATE:"Subcatgory not update",
    SUBCATEGORY_UPDATE_SUCCESS:"Subcategory data update successfully",
    SUBCATEGORY_IS_REQUIRE:"Subcategory id is require.",
    PRODUCT_NOT_UPDATE:"Product not update",
    PRODUCT_UPDATE_SUCCESS:'Product update sucessfully.'
}




module.exports = { status_codes, status_message }